### PR TITLE
Fix/include types in package json

### PR DESCRIPTION
**Pull request by mateuszkulpa**
Update package.json and include also files with d.ts extension. 
Without it we fetch only .js files and types don't work in projects.

### CODE REVIEW

**Review by pajm0n — APPROVED** [review]

**Review by AlanLes — APPROVED** [review]
LGTM, great job! 👍 😊

**Comment by AlanLes** [comment]
@mateuszkulpa You could also bump version in package.json, then run npm install and commit and push changes made in `package.json` along with `package-lock.json` ;)

**Comment by mateuszkulpa** [comment]
@AlanLes Version bumped, thanks!

**Comment by pspaczek** [comment]
thanks @mateuszkulpa for your PR :)

**Pull request merged**
