### PR TITLE
Bugfix/undefined-bowser-in-track-event-method

### PR DESCRIPTION
**Pull request by AlanLes**
Things done: 
- improve initializing async calls
- fix undefined browser in trackEvent method (fix error from below screenshot)

image

### CODE REVIEW

**Review by pajm0n — APPROVED** [review]
These changes look okay to me :)

**Review by mateuszkulpa — COMMENTED** [review]
LGTM ;)
I have only one question
1. Do we really need async imports for bowser and firebase packages? Webpack treeshaking won't remove these modules if infermedica analytics are disabled?

**Comment by AlanLes** [comment]
@mateuszkulpa to be honest I didn't check that, it was done this way when I started working on this task, so I assumed it's the desired solution, and I assumed that it's done this way exactly because webpack treeshaking won't remove these modules

**Comment by pspaczek** [comment]
@mateuszkulpa we should to rewrite this module to support all webpack performance features. But we do it in Q1 2022 :)

**Pull request merged**
